### ISSUE TITLE
error: expose_camera_stream_source - Integration

### ISSUE THREAD

**Issue by tommymogensen** [felipecrs/hass-expose-camera-stream-source#1]
Hi There
Trying to implement this and get my TUYA cam in grigate :)
when i update my configuration.yaml i get thoe below error at restart.

First i just pasted "expose_camera_stream_source:" into the end of my config ...thats not working.
then "expose_camera_stream_source: camera.denver_shc_150" ...thats not working.
so i am a bit usunre what i am doing wrong?

Failed to restart Home Assistant
The system cannot restart because the configuration is not valid: Integration error: expose_camera_stream_source - Integration 'expose_camera_stream_source' not found.

**Comment by felipecrs** [comment]
1. Install from HACS
2. Restart HA
3. Add `expose_camera_stream_source:` in your configuration.yaml (do not add anything else)
4. Restart HA

Can you double check you followed these steps?

**Comment by felipecrs** [comment]
> First i just pasted "expose_camera_stream_source:" into the end of my config ...thats not working.

If it continues to fail here, let me know what exactly is not working. Check your HA logs for hints.

**Comment by tommymogensen** [comment]
the issue is that i cant restart HA after update of config.
i bet that i am doing something wrong it just says:

Failed to restart Home Assistant
The system cannot restart because the configuration is not valid: Integration error: expose_camera_stream_source - Integration 'expose_camera_stream_source' not found.

**Comment by felipecrs** [comment]
Are you sure you restarted HA after installing from HACS?

**Comment by felipecrs** [comment]
Oh, of course, remove `expose_camera_stream_source:` from your `configuration.yaml` if you have added it before restarting after installing with HACS.

**Comment by tommymogensen** [comment]
ok sorry about that!
it seems that it where NOT isntalled even though i where sure that i installed it.


Thank you!

**Comment by felipecrs** [comment]
Weird. Anyway, let me know if you managed to add your Tuya camera to Frigate after all. :)

**Comment by tommymogensen** [comment]
so folowing the guide: https://github.com/felipecrs/hass-expose-camera-stream-source

I guess that the ip...is the IP of my homeassistant installation keeping the port as that is the port of the RTSP stream that you create?
in my case my home assistant in running on 192.168.0.24 i guess i could be using "homeassistant.local"

so it should be as below?

# frigate.yml

my_camera:
  ffmpeg:
    inputs:
      - path: rtsp://192.168.0.24:8554/my_camera

**Comment by felipecrs** [comment]
Your example seems correct to me. I'm not sure if `homeassistant.local` would work, feel free to test though.

**Comment by tommymogensen** [comment]
ill give it a try if /when all is working

**Comment by tommymogensen** [comment]
i got Frigate running though the feed is just green.

Sanity check:
should i be able in like VLC player to open:
rtsp://192.168.0.24:8554/camera.denver_shc_150

"camera.denver_shc_150" is the entity name i HA

**Comment by felipecrs** [comment]
Yes you should be able to view the RTSP link in VLC first. But the URL should have the name of the stream you configured in go2rtc, not the name of the HA camera. Unless you configured the name in go2rtc to be exactly equal the name in HA.

**Comment by tommymogensen** [comment]
# go2rtc.yaml

streams:
  my_camera:
    - echo:bash /config/custom_components/expose_camera_stream_source/get_stream.sh camera.denver_sho_110
    
So in thise case it will be:
    rtsp://192.168.0.24:8554/my_camera

**Comment by felipecrs** [comment]
Correct.

Em sáb., 19 de nov. de 2022 18:23, tommymogensen ***@***.***>
escreveu:

**Comment by tommymogensen** [comment]
i got it working in frigate now!
How do i send you a beer?

**Comment by felipecrs** [comment]
Hahaha. Great! I'm happy it worked for you!

If you can star the repo that would be already awesome. Thanks!
