### ISSUE TITLE
Transmission stream resolution

### ISSUE THREAD

**Issue by rodrigofragadf** [felipecrs/hass-expose-camera-stream-source#10]
I'm getting the rtsp stream correctly but it's in SD quality, is there any way to get the stream in HD quality?

**Comment by felipecrs** [comment]
I suppose you are talking about Tuya, right? Unfortunately, no. This would be an issue to the Tuya integration for Home Assistant or for the Tuya API itself.

You are not the first one to ask this by the way, lol.

Another possible solution would be for go2rtc to support Tuya directly: https://github.com/AlexxIT/go2rtc/issues/315
