### ISSUE TITLE
Any way to use this with the go2rtc bundled in frigate

### ISSUE THREAD

**Issue by dasb00ter** [felipecrs/hass-expose-camera-stream-source#12]
I would like to get my nest hub max camera pulled into frigate. I am running Home assistant as a VM with addons/integrations available. I am running frigate which is now bundling go2rtc (which I have updated to 1.62) separately in docker. I think I need go2rtc to restream hub max camera stream to frigate so I think I need something like this...but I could be wrong

**Comment by felipecrs** [comment]
Can you view your nest hub max camera through Home Assistant without using RTSPToWebRTC? If yes, than you can use this integration.

Otherwise, try directly with: https://github.com/AlexxIT/go2rtc?tab=readme-ov-file#source-hass

**Comment by felipecrs** [comment]
> Any way to use this with the go2rtc bundled in frigate

Answering your question, yes, use the first method as if you were running the go2rtc add-on:

https://github.com/felipecrs/hass-expose-camera-stream-source?tab=readme-ov-file#when-go2rtc-is-installed-as-an-add-on

I'll try to improve docs later.

**Comment by dasb00ter** [comment]
> > Any way to use this with the go2rtc bundled in frigate
> 
> Answering your question, yes, use the first method as if you were running the go2rtc add-on:
> 
> https://github.com/felipecrs/hass-expose-camera-stream-source?tab=readme-ov-file#when-go2rtc-is-installed-as-an-add-on
> 
> I'll try to improve docs later.

My first thought is frigate (with bundled go2rtc) is in running in docker which is completely separate from my virtual machine running Hassio. How would go2rtc communicate using that line in yaml. I will look again

**Comment by felipecrs** [comment]
If you are running Frigate with docker, then follow the guide for gortc with docker.

**Comment by dasb00ter** [comment]
Ok ... So the changes to the docker compose to mount the script would have to go in the frigate docker compose then

**Comment by felipecrs** [comment]
Yes.

**Comment by felipecrs** [comment]
> Yes I have access to the Google max hub camera in Hassio through the nest integration(API). It's not great though. I'm thinking the hub max uses rtsp not webrtc but I'm having trouble figuring that out.

This depends on the device itself. Some has rtsp, some has webrtc. But really, in your case I'd go with the hass source in go2rtc.

See if it doesn't work with that first.
