### ISSUE TITLE
Camera not loading

### ISSUE THREAD

**Issue by reesion** [felipecrs/hass-expose-camera-stream-source#13]
Hi,

I have this setup with multiple cameras and one of my camera is not loading and showing error - "mse: streams: exit status 22".

Any idea what that means?

Thanks

**Comment by felipecrs** [comment]
Are you able to view your camera from within Home Assistant itself (without go2rtc or this integration)?

**Comment by reesion** [comment]
Yes it works without any integration.

**Comment by felipecrs** [comment]
Are we talking about a Tuya camera?

**Comment by reesion** [comment]
Nope. It is one of the Google Nest cameras

**Comment by felipecrs** [comment]
Can you click in "info" in the go2rtc and show me how the URL looks like? Example:

![image](https://github.com/felipecrs/hass-expose-camera-stream-source/assets/29582865/421a97a1-5bb2-41dc-bd07-e90bb866e900)

**Comment by felipecrs** [comment]
I believe your camera is not an RTSP one, but WebRTC. In this case, try importing in go2rtc using `hass`.

https://github.com/AlexxIT/go2rtc?tab=readme-ov-file#source-hass

If that's not your case, please show me how the camera stream URL looks like. Running this command in Terminal add-on should yield it:

```console
bash /config/custom_components/expose_camera_stream_source/get_stream.sh camera.my_camera_entity_name
```

**Comment by reesion** [comment]
> https://github.com/AlexxIT/go2rtc?tab=readme-ov-file#source-hass

That's it. That fixed it. You're a legend! 

Thank you so much!
