### ISSUE TITLE
Needs to be an add-on under the supervisor ?

### ISSUE THREAD

**Issue by stevenbrown1862** [felipecrs/hass-expose-camera-stream-source#3]
Hi.  I think the question in the heading sums it up.  I'm running home assistant and Go2RTC as separate docker containers and couldn't as yet get this to work (even though I'm desperate to for my Nest cameras).  Before I spend time persevering, can I just check my suspicion that this needs to be run as an addon with supervisor and so therefore isn't for me ?

Thanks for the work either way.

**Comment by felipecrs** [comment]
The convenience script provided by the integration used in the example is only supported in the add-on indeed. But you can easily work around it.

Copy the script to a location your go2rtc has access.

Change the URL to match the HA URL that go2rtc has access.

Generate a long-lived token in your profile page and use it as the token for the curl authentication.

I will mention this in the readme (that the convenience script is only for add-on users + how to use without the convenience script)

**Comment by felipecrs** [comment]
> I will mention this in the readme (that the convenience script is only for add-on users + how to use without the convenience script)

But please don't wait for it, you can go ahead and try to to implement it by yourself based on my suggestions above. If you ever do, you are also welcome to send a PR improving the documentation. :)

**Comment by stevenbrown1862** [comment]
Thanks.   Once I managed to map the script into the container this worked as you suggested.  I'll give it a couple of days days to see whether the stream is stable and revisit.  Never done a PR so that'll be a challenge.

**Comment by felipecrs** [comment]
Closed by https://github.com/felipecrs/hass-expose-camera-stream-source/pull/4
