### ISSUE TITLE
View your camera stream in Home Assistant using HLS.

### ISSUE THREAD

**Issue by kadkin-a** [felipecrs/hass-expose-camera-stream-source#35]
How can I check this?
In homeassitant I have camera entities. In lovelase I can view them. But the link still doesn't work
![каамеры](https://github.com/felipecrs/hass-expose-camera-stream-source/assets/123934211/4fb79c02-a4bc-4d44-a9ce-22dbc9dc8801)
![go2rtc](https://github.com/felipecrs/hass-expose-camera-stream-source/assets/123934211/8fedca8a-086c-443f-94df-4d0d89b2a060)
in go2rtc a have error
![error](https://github.com/felipecrs/hass-expose-camera-stream-source/assets/123934211/d0a898fc-4ca2-4dcb-bbd9-1ca48fea06b3)

**Comment by felipecrs** [comment]
Run the script by yourself, catch the URL and try playing it in VLC.

Does it work there?

What integration provides this camera?

What kind of URL do you get?

**Comment by kadkin-a** [comment]
I run script in terminal
![image](https://github.com/felipecrs/hass-expose-camera-stream-source/assets/123934211/b9f87cb0-61ce-4959-ba20-ff81d3262871)

**Comment by kadkin-a** [comment]
I run script on VScode . I get URL ? its works fine
![image](https://github.com/felipecrs/hass-expose-camera-stream-source/assets/123934211/5f244338-6d8b-4068-853f-06708158f515)

**Comment by felipecrs** [comment]
That's great news. It means this integration is working just fine and it's correctly passing the stream URL to go2rtc.

However, go2rtc is not being able to play it well.

Search go2rtc documentation and existing issues, and if there is none open already, I suggest you open one issue there.

**Comment by kadkin-a** [comment]
Greetings to you Felipe.
Could you please help me a little. Oh, I don't know python at all. According to the description 
https://github.com/AlexxIT/go2rtc?tab=readme-ov-file#source-echo
I need to add "fmmpeg:" before the link. 
I can't imagine how I need to do this

**Comment by felipecrs** [comment]
You can copy the `get_stream.sh` script and make the following change at the end:

```diff
#!/usr/bin/env bash

set -eu

SUPERVISOR_TOKEN="${SUPERVISOR_TOKEN:?"SUPERVISOR_TOKEN is not set, you need to run this script from an add-on."}"
entity_id="${1}"

- exec curl -fsSL -H "Authorization: Bearer ${SUPERVISOR_TOKEN}" "http://supervisor/core/api/camera_stream_source/${entity_id}"
+ stream_url=$(curl -fsSL -H "Authorization: Bearer ${SUPERVISOR_TOKEN}" "http://supervisor/core/api/camera_stream_source/${entity_id}")
+
+ echo -n "ffmpeg:${stream_url}#audio=copy#video=h264#hardware"
```

No need for a Python script.

**Comment by kadkin-a** [comment]
Sorry, I forgot to say thank you.
Everything worked fine for me.
Thank you very much for your efforts.
Unfortunately, I can’t send you a cup of coffee from Russia

**Comment by felipecrs** [comment]
It's alright, don't worry. I'm happy it worked for you!
