### ISSUE TITLE
frigate as seperate server with go2rtc

### ISSUE THREAD

**Issue by Ostedtinkerer** [felipecrs/hass-expose-camera-stream-source#37]
Hi!
Great project!

Is this possible to achieve with a frigate instance outside of homeassistant?

I'm running frigate within proxmox as an lxc, with go2rtc.

Frigate and homeassistant does have different local ip's.

**Comment by felipecrs** [comment]
Yes, you can adapt from [_When go2rtc is running via docker_](https://github.com/felipecrs/hass-expose-camera-stream-source?tab=readme-ov-file#when-go2rtc-is-running-via-docker).

**Comment by Ostedtinkerer** [comment]
I got that working! Thanks!

I'm now running into a "permission denied" prompt within go2rtc webui.
Script is updated according to docs and so are docker. with mapping and env. 

do you have a clue?
- i dont get anything log related in homeassistant. Frigate/go2rtc provides a 404not found message in logs.

In configuration.yaml i've set add-on line.
- Should the camera entities be exposed there? docs dont say so i didnt.

**Comment by felipecrs** [comment]
```
chmod +x path/to/script.sh
```

No?

**Comment by Ostedtinkerer** [comment]
I have made it executeable.



Sendt fra Outlook til Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by felipecrs** [comment]
That's what permission denied error usually means. If it didn't work, try:

```diff
- echo:/config/get_ha_stream.sh camera.my_camera
+ echo:bash /config/get_ha_stream.sh camera.my_camera
```

**Comment by felipecrs** [comment]
Well, try executing the script by yourself. If it's outputting an stream URL, the script and this integration is working fine.

What is the camera's integration?

**Comment by Ostedtinkerer** [comment]
I will try that tomorrow.

I will let you know. Thanks!

Sendt fra Outlook til Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Ostedtinkerer** [comment]
The camera integration is tuya. There official integration.
Should i use localtuya?

when i run the script in cmdline i get this result. --- bash ./get_ha_stream.sh

./get_ha_stream.sh: line 2: $'\r': command not found
: invalid optionsh: line 3: set: -
set: usage: set [-abefhkmnptuvxBCEHPT] [-o option-name] [--] [-] [arg ...]
./get_ha_stream.sh: line 4: $'\r': command not found
./get_ha_stream.sh: line 5: HA_TOKEN: "XXXXXXXXXXXXXX"

it looks like something is wrong with the script.
i've copied the script, and changed ha-token, and updated ip.
Should there be any other changes?

**Comment by felipecrs** [comment]
I think you are working on Windows and the line breaks in your script are CRLF, which Linux doesn't understand. Try opening the script in VSCode and replacing the line breaks from CRLF to LF. You can search online abou this too.

**Comment by Ostedtinkerer** [comment]
it is correct that im on windows. I use MobaXterm for ssh access to my frigate machine. Frigate runs a debian12 lxc.

**Comment by felipecrs** [comment]
If you want to write the token in the script, here's how it should be:

```diff
- HA_TOKEN="${HA_TOKEN:?"HA_TOKEN is not set, make sure to have this environment variable set with your Home Assisant long-lived token."}"
+ HA_TOKEN='your token contents here'
```

**Comment by felipecrs** [comment]
Closing as I don't think there's anything to be done here.
