### ISSUE TITLE
integration stopped working as of 2024.10.3

### ISSUE THREAD

**Issue by tiotiito** [felipecrs/hass-expose-camera-stream-source#43]
The integration stopped working as of 2024.10.3
I use a Tuya camera and used When go2rtc is installed as an add-on. It worked perfectly until 2024.10.2
I updated to the latest version 2024.11.2 and it still doesn't work
Now the message appears   streams: exit status 22
some solution?

**Comment by felipecrs** [comment]
I just tested here for a Tuya camera in 2024.11.2 and it's working fine.

Try calling the script in the Terminal add-on:

```
bash /config/custom_components/expose_camera_stream_source/get_stream.sh camera.my_camera_entity
```

Double check your entity id btw.

**Comment by tiotiito** [comment]
Hello, before the update the data was being read from   /config/get_ha_stream.sh
I copied the configuration I had there and pasted it in /config/custom_components/expose_camera_stream_source/get_stream.sh
It's working now, thanks for watching.

**Comment by SgtBatten** [comment]
I recently updated HA and having the same issue. Suddenly not working and after finding this thread I can see my get_ha_stream file is simply missing altogether. It worked fine for years until now. I don't even remember how it's set up lol

**Comment by SgtBatten** [comment]
It has been a while since updating and it turned out my yaml configuration was no longer supported and I had to add the integration via the UI and it works again. Still using the original script.
