### ISSUE TITLE
Tuya: EOF on RTSP stream 

### ISSUE THREAD

**Issue by leonardpitzu** [felipecrs/hass-expose-camera-stream-source#45]
I've got a Philips branded Tuya baby monitor. It works as expected with both Tuya Smart and the Philips Avent app (currently using Tuya Smart). I can successfully get the rasps url but cannot stream anything as I only get a EOF error (with both your script + go2rtc and FFMPEG). Apparently the streaming url is not got or something else is broken as streaming only works in the Tuya app and in no other app/script/tool.
Any hint to debug it or figure out what the problem is?

**Comment by felipecrs** [comment]
Which script are you referring to?

[get_stream.sh](https://github.com/felipecrs/hass-expose-camera-stream-source/blob/master/custom_components/expose_camera_stream_source/get_stream.sh) or [get_tuya_stream_url.py](https://github.com/felipecrs/hass-expose-camera-stream-source/blob/master/custom_components/expose_camera_stream_source/scripts/get_tuya_stream_url.py)?

**Comment by felipecrs** [comment]
Have you tried with HLS?

![image](https://github.com/user-attachments/assets/f257320e-a745-4bc5-8c17-e66c54663891)

**Comment by felipecrs** [comment]
By the way, during testing phase, don't hook go2rtc yet. Call the script and try to play the output in something like VLC (just be fast, because the URL for Tuya streams expires in a few seconds).

**Comment by leonardpitzu** [comment]
I tried with HLS and RTSP. Both with the Python script. I tried with VLC and none is working. 
I can share the camera if you give me an email address.

**Comment by felipecrs** [comment]
Both output a stream link, but none works, right?

**Comment by leonardpitzu** [comment]
Yes, both output a link and none works.

**Comment by felipecrs** [comment]
Got it. In this case, there's nothing I can do for you. The purpose of my scripts is to give you the stream URLs. If they don't work, that's beside the point. Sorry. :(

However, I have some suggestions for you:

1. Try this WIP WebRTC Tuya source for go2rtc: https://github.com/AlexxIT/go2rtc/pull/1379 
2. I never tried, but there's this one too: https://github.com/AlexxIT/go2rtc/pull/1412

**Comment by felipecrs** [comment]
Oh, by the way, do you have Live Stream API active?

![image](https://github.com/user-attachments/assets/66847929-f533-4c59-b911-6b7a47c48e5e)

**Comment by leonardpitzu** [comment]
<img width="1723" alt="image" src="https://github.com/user-attachments/assets/885cad25-0555-4b73-95b4-71c64ebf70fc">

**Comment by felipecrs** [comment]
Alright. If you ever find a solution for this, I'd appreciate you let me know how. Good luck!
