### ISSUE TITLE
Stopped working

### ISSUE THREAD

**Issue by rfam13** [felipecrs/hass-expose-camera-stream-source#46]
Hello, 

I have been using this for a long time and just recently it stopped providing the stream from my Google Hub Max video stream.  In go2rtc it just shows 

"streams: exit status 22"

I have confirmed the entity through the Nest integration (camera.living_room) is still functional and showing live video, and it is.

Is this still working for everyone else using nest cams?

**Comment by felipecrs** [comment]
Maybe your Google Hub Max got upgraded and now it no longer provides an RTSP URL.

Try calling the script manually once and validating the result. Try playing the result in VLC.

**Comment by rfam13** [comment]
Yep looks like it switched to WebRTC when migrated to the home app.

Thanks for the tip.

**Comment by felipecrs** [comment]
Now that it's migrated to WebRTC, you can import it directly in go2rtc. There's no more need for this integration.

https://github.com/AlexxIT/go2rtc#source-nest
