### ISSUE TITLE
How to use this to add a camera to hass?

### ISSUE THREAD

**Issue by jdeneef** [felipecrs/hass-expose-camera-stream-source#47]
I used your python script to extract an rtsp steam from a tuya cloud connected petfeeder, which works perfectly, stream can be played using `ffplay`. However, I fail to understand how to add this stream to a regular generic hass rtsp camera? Can you share how to? Or point me in the right direction? 

fwiw, this works (had to add live video api to my tuya iot cloud setup):
```sh
ffplay `python get_tuya_stream_url.py <device-id> <tuya-key> <tuya-secret> https://openapi.tuyaxx.com RTSP`
```
I want to use that rtsp stream url in a homeassistant camera stream, but this is a one-time use url, so needs to be generated at every new camera access

**Comment by felipecrs** [comment]
My script is intended to be used with go2rtc. Once it's working in go2rtc, then you can import the stream from go2rtc to Home Assistant following [this](https://github.com/AlexxIT/go2rtc#:~:text=Hass%20%3E%20Settings%20%3E%20Integrations%20%3E%20Add%20Integration%20%3E%20Generic%20Camera).

![image](https://github.com/user-attachments/assets/5deb35f4-47ab-4a7d-973f-b24cc59967cc)

**Comment by felipecrs** [comment]
@jdeneef, did it work?

**Comment by jdeneef** [comment]
Sry, did not test, was mostly looking for the quick hack to get a dynamic url into the generic camera. Quickly checked go2rtc, seems like quite heavy to add 1 camera  .. will check later, or try and add some logic on top of generic camera. Thanx for the explanation though!

**Comment by felipecrs** [comment]
Well, go2rtc is not heavy, and it's simple to install and use. Either via the WebRTC integration, or via the go2rtc add-on.

I strongly suggest you give it a try.

Anyway, good luck and happy holidays!

**Comment by jdeneef** [comment]
seeing hass 2024.11 has go2rtc included ;-) this might need a 2nd change. Still would prefer not a cloud generated link, guessing that the api might cost me and will be closed down at some time. However, where do I add the streams for go2rtc?? I can change go2rtc config adding eg debug_ui, but streams return error in the go2rtc.yaml ..

**Comment by felipecrs** [comment]
You cannot use the builtin go2rtc for this at this moment. You need to install it as I suggested.

**Comment by jdeneef** [comment]
ok, thanx for sharing!
