### ISSUE TITLE
[Question] Nest cameras

### ISSUE THREAD

**Issue by pissten** [felipecrs/hass-expose-camera-stream-source#48]
Hi,

I'm not labeling this as a bug. more like a question.
I've used this integration and the custom script to retreive some of my cameras,
and integrate them in my docker container instance of go2rtc.
One thing i could never achieve though was to retreive the google nest cams using the script.
To get them integrated in go2rtc I had to use the hass:// url method. 
Error message when running script for nest cams:

`mse: streams: exit status 22`

**Comment by felipecrs** [comment]
This is normal. It means your Nest cameras are not RTSP-enabled.

In this case, you should either use hass:// or nest:// directly in go2rtc.

I've heard that hass:// stopped working well. If you are experiencing issues with it, try the nest:// source.

**Comment by watsondan** [comment]
@felipecrs Hello,

Are there any updated examples on how to use the Nest configuration? [Source: Nest
](https://github.com/AlexxIT/go2rtc?tab=readme-ov-file#source-nest)

I see you mention: `nest://` but in the documentation it shows `nest:?`

I have all my IDs' and tokens from my Google world.

**Comment by felipecrs** [comment]
Sorry, that was a mistake from my side. I meant `nest:`.

But this is not the correct place to look for it.

Check go2rtc issues, there's plenty of people talking about it there.

**Comment by felipecrs** [comment]
I don't own any nest cameras myself. Cannot help much.

**Comment by watsondan** [comment]
> go2rtc issues

Thank you for all your work, and time!

**Comment by felipecrs** [comment]
> Check go2rtc issues, there's plenty of people talking about it there.

Specifically this one: https://github.com/AlexxIT/go2rtc/issues/1440
