### ISSUE TITLE
Issue with Google Nest cam: curl: (22) The requested URL returned error: 404

### ISSUE THREAD

**Issue by rickitaly** [felipecrs/hass-expose-camera-stream-source#5]
Hello, have a problem with getting RTSP stream from a Nest Cam that is working fine in HA as WebRTC.
In HA it is streaming as camera.soggiornocam.
I installed this extension from HACS.
Followed the instructions with the double restart.

Install also go2rtc, and then create the following go2rtc.yaml

`streams:
  my_camera:
    - echo:bash /config/custom_components/expose_camera_stream_source/get_stream.sh camera.soggiornocam
 `
If i try to access to my_camera from go2rtc i cannot see any streaming, 
If i access to HA terminal and try to run
`bash get_stream.sh camera.soggiornocam
`
then i get:
`curl: (22) The requested URL returned error: 404`

Is this solution compatible with Google cams? Any help?

Just to confirm everything, if i switch just the camera.soggiornocam to another camera entity which is not from google, everything works fine! I get all the streams, so i guess the issue is related to the camera coming from Google Nest integration.

Thanks!

**Comment by felipecrs** [comment]
Hm... are you sure the integration is enabled in your `configuration.yaml`? 404 can mean a lot of things. To be sure the integration is working, can you try to create a fake camera and check?

rtsp://wowzaec2demo.streamlock.net/vod/mp4:BigBuckBunny_115k.mp4

https://user-images.githubusercontent.com/29582865/205690561-da88f1a1-57e6-40f2-b714-56a9ff3744cb.mp4

**Comment by rickitaly** [comment]
Thanks for your reply, i just edited the post above
Just to confirm everything, if i switch just the camera.soggiornocam to another camera entity which is not from google, everything works fine! I get all the streams, so i guess the issue is related to the camera coming from Google Nest integration.

**Comment by felipecrs** [comment]
Is RTSPToWebRTC enabled in your HA?

https://www.home-assistant.io/integrations/rtsp_to_webrtc/

You can use go2rtc as the server for it:

https://github.com/AlexxIT/go2rtc#from-hass-to-go2rtc

**Comment by felipecrs** [comment]
Anyway, my advice is: try to fetch the URL once with RTSPToWebRTC enabled and try once again with it disabled. See if it changes anything.

**Comment by rickitaly** [comment]
yes it is enabled
![image](https://user-images.githubusercontent.com/46688153/205693400-3bb593bf-9d20-4696-b3e9-74c79c76e0f0.png)
tried also after disabling, no difference to get stream, still 404

**Comment by stevenbrown1862** [comment]
> That's sad. :(
> 
> stevenbrown1862 reported in #3 that it worked for a Nest camera.
> 
> @stevenbrown1862 is there advice you can share with @rickitaly? I don't have a Nest cam myself.
> 
> If we conclude that it's not supported at all I'll remove the mention of it from the readme.

Hi both,
Just to confirm that I have this working fine with both my Nest Hello (wired doorbell) and my Nest Hub Max.  I didn't do anything special beyond the instructions in the readme to get this working.    I'm in work at the moment but will have a look at my configs this evening just to make sure there's nothing that I've forgotten.

**Comment by rickitaly** [comment]
Hello  @stevenbrown1862  ! Thanks for sharing.
Indeed looking at Google Nest docs, the Wired Doorbell is part of RTSP devices, while my Nest Cam Indoor is WebRTC based.
So i guess that is the difference, and i still cannot find a way to get this stream to Frigate or any other device :-(
![image](https://user-images.githubusercontent.com/46688153/205696783-88557c4b-04c1-46eb-b83f-2f1f2ecfd438.png)

**Comment by felipecrs** [comment]
Hm... if it isn't RTSP and there isn't an URL, I wonder how go2rtc can stream it using Picture Glance card with RTSPToWebRTC enabled. @alexxit, perhaps you have any idea?

**Comment by AlexxIT** [comment]
@rickitaly well. If you or some one else can share Nest API credentials with me (for Hass integration), maybe I can implement WebRTC source for go2rtc.

**Comment by AlexxIT** [comment]
I don't think I could implement such a complicated thing blindly without access to API.

**Comment by felipecrs** [comment]
Yeah. You are right.

**Comment by AlexxIT** [comment]
You can create separate Google account. As I understand it will cost you $5.

**Comment by pergolafabio** [comment]
> @rickitaly well. If you or some one else can share Nest API credentials with me (for Hass integration), maybe I can implement WebRTC source for go2rtc.

Hey @AlexxIT , I have an tuya wifi petfeeder, it doesnt support local rtsp, it doesn't support fetching the rtsp url from tuya cloud...  I can only fetch with tuya API the turn/stun address for the webrtc config with the credentials... I can provide you details if you want to setup a pure webrtc cam?... Would be great if I can add this cam to HA

**Comment by AlexxIT** [comment]
@pergolafabio yes. You can share info in telegram or discord. Check contacts on my github.

**Comment by pergolafabio** [comment]
Ok, will do later, thnx

**Comment by felipecrs** [comment]
As there is nothing that can be made from this project's side, I'm closing this issue.

I added a section in README to make this clear.

https://github.com/felipecrs/hass-expose-camera-stream-source#:~:text=go2rtc%20and%20Frigate.-,Note%2C%20however,-%2C%20that%20this%20will
