### ISSUE TITLE
404 Error

### ISSUE THREAD

**Issue by adi90x** [felipecrs/hass-expose-camera-stream-source#7]
Hello, 

It seems that http://ip_adress:8123/api/camera_stream_source/${entity_id}  is no longer existing in 2023.2 as I got an error  ```curl: (22) The requested URL returned error: 404 Not Found``` while trying to curl the endpoint.
Is it a know issue ? 

Regards,
Adrien

**Comment by adi90x** [comment]
My bad no idea what I did but it is working fine now :)

**Comment by felipecrs** [comment]
:)
