### ISSUE TITLE
Birdfeeder camera - low quality, battery drained

### ISSUE THREAD

**Issue by szupi-ipuzs** [felipecrs/hass-expose-camera-stream-source#8]
Hi,
First I want to say big THANK YOU for this integration. I have a birdfeeder with Tuya camera and was looking for a way to connect it to Frigate. This is it!
I managed to run the stream through go2rtc and to frigate using your integration. But my joy was short-lived, as Frigate was not detecting any birds . Then I realized the quality of the stream that HA provides is pretty low - much worse than what I can see in the Tuya app. Do you know if this can be changed somewhere in HA? Or is it a problem of Tuya integration in HA?
Also after a few hours I noticed that the battery in camera is getting very low. It seems the camera has never stopped streaming even though noone was watching (neither via app or otherwise), thus draining the battery. Am I correct to assume this is an issue of HA integration? Or is there something you can do about it?

**Comment by felipecrs** [comment]
> Do you know if this can be changed somewhere in HA?

I don't think there is an option to change the quality of the stream for the Tuya integration.

> Or is it a problem of Tuya integration in HA?

Not a problem specifically, but maybe a feature request. As the ONVIF integration adds two camera entities to HA for the different streams, I think the Tuya integration should add too (as long as the Tuya Cloud API that it relies on also supports it).

> Am I correct to assume this is an issue of HA integration?

This is not an issue with the Tuya integration, neither an issue with this integration. It's a known issue of Frigate:

- https://github.com/blakeblackshear/frigate/issues/4325

**Comment by felipecrs** [comment]
As there is nothing that this integration can do to help, I'm closing this issue. Thanks for the feedback on it though!
